// DriveUnitAddresses table extracted from Bosch DiagnosticTool 3 (v17.9.3),
// com.bosch.ebike.messagebus.constants.DriveUnitAddresses (decompiled, read-only
// reference use — see ../../RESEARCH.md for provenance and methodology).
// Pure data, no dependencies — reusable from Node or browser (WebUSB) code alike.

const DRIVE_UNIT_ADDRESSES = [
  { name: 'ACTIVE_ASSIST_MODES', addr: 6222 },
  { name: 'ADDING_ASSIST_MODES_LOCKED', addr: 6207 },
  { name: 'ALWAYS_SHOW_BIKE_SPEED_IN_DISPLAY', addr: 6171 },
  { name: 'ASSIST_MODE', addr: 6153 },
  { name: 'ASSIST_MODE_COLORS', addr: 6158 },
  { name: 'ASSIST_MODE_IS_OEM_ADJUSTABLE', addr: 4246 },
  { name: 'ASSIST_MODE_LONG_NAMES', addr: 6157 },
  { name: 'ASSIST_MODE_SHORT_NAMES', addr: 6156 },
  { name: 'ASSIST_MODE_STRENGTH', addr: 4245 },
  { name: 'AVAILABLE_ASSIST_MODES_LOWER', addr: 6248 },
  { name: 'AVAILABLE_ASSIST_MODES_UPPER', addr: 6159 },
  { name: 'AVERAGE_RIDER_CADENCE', addr: 6262 },
  { name: 'BATTERY_KEY_LOCK_NUMBER', addr: 6195 },
  { name: 'BIKE_CATEGORY', addr: 6229 },
  { name: 'BIKE_CATEGORY_CONFIGURATION', addr: 6211 },
  { name: 'BIKE_ID', addr: 6188 },
  { name: 'BIKE_LIGHT', addr: 6172 },
  { name: 'BIKE_LIGHT_AVAILABLE', addr: 6176 },
  { name: 'BIKE_LIGHT_CONFIGURATION', addr: 6177 },
  { name: 'BIKE_LIGHT_CONFIGURATION_OEM', addr: 6175 },
  { name: 'BIKE_LIGHT_POWER', addr: 6178 },
  { name: 'BIKE_SPEED', addr: 6152 },
  { name: 'BOOTLOADER_SOFTWARE_VERSION', addr: 6151 },
  { name: 'COMPONENT_LOCKED', addr: 6196 },
  { name: 'COMPONENT_LOCK_CONFIGURATION', addr: 6197 },
  { name: 'CONNECT_MODULE_READY', addr: 6216 },
  { name: 'CURRENT_MOUNTING_ANGLE_AT_STANDSTILL', addr: 4257 },
  { name: 'DISPLAYED_BIKE_SPEED', addr: 6189 },
  { name: 'DISTRACTED_RIDING_ALERT', addr: 6161 },
  { name: 'DRIVE_UNIT_FEATURE_PROPERTIES_RELEASE1', addr: 6162 },
  { name: 'DRIVE_UNIT_FEATURE_PROPERTIES_RELEASE2', addr: 6256 },
  { name: 'DRIVE_UNIT_FEATURE_PROPERTIES_RELEASE3', addr: 6257 },
  { name: 'DRIVE_UNIT_STATIC_FEATURE_PROPERTIES', addr: 6272 },
  { name: 'EXECUTE_INFORMATION_MANAGER_COMMAND_BOSCH', addr: 4229 },
  { name: 'EXECUTE_INFORMATION_MANAGER_COMMAND_IBD', addr: 4226 },
  { name: 'EXECUTE_INFORMATION_MANAGER_COMMAND_OEM', addr: 4227 },
  { name: 'EXECUTE_INFORMATION_MANAGER_COMMAND_SP', addr: 4228 },
  { name: 'EXTENDED_BIKE_SPEED', addr: 6264 },
  { name: 'FRONT_ANTI_LOCK_BRAKE_SYSTEM_ASSEMBLED', addr: 6228 },
  { name: 'GEARING_SYSTEM', addr: 6187 },
  { name: 'GEARSHIFT_APPLICATION_AVAILABLE', addr: 6203 },
  { name: 'GEARSHIFT_APPLICATION_REQUIRED', addr: 6202 },
  { name: 'GET_ASSIST_MODE_INFORMATION', addr: 4235 },
  { name: 'GET_ASSIST_MODE_STATISTICS', addr: 4236 },
  { name: 'HARDWARE_SOFTWARE_VERSION', addr: 6149 },
  { name: 'HARDWARE_VERSION', addr: 6148 },
  { name: 'HIGH_POWER_PORT_ACTIVE', addr: 6194 },
  { name: 'HUB_CONFIGURABLE_PORT_STATUS', addr: 6298 },
  { name: 'IN_SOFTWARE_INSTALLATION_STATE', addr: 6212 },
  { name: 'IS_SAMPLE_SOFTWARE', addr: 6198 },
  { name: 'LOW_POWER_PORT_ACTIVE', addr: 6193 },
  { name: 'MANUFACTURING_DATE', addr: 6199 },
  { name: 'MAXIMUM_ASSISTANCE_SPEED', addr: 6167 },
  { name: 'MAXIMUM_ASSISTANCE_SPEED_IBD', addr: 6210 },
  { name: 'MAXIMUM_AVAILABLE_MOTOR_POWER', addr: 6260 },
  { name: 'MAXIMUM_AVAILABLE_MOTOR_TORQUE', addr: 6263 },
  { name: 'MAXIMUM_GEAR_RATIO', addr: 6166 },
  { name: 'MAXIMUM_LEGAL_BIKE_SPEED', addr: 6163 },
  { name: 'MOTOR_CUT_OFF_DISTANCE', addr: 6227 },
  { name: 'MOTOR_POWER_CONFIGURATION', addr: 6226 },
  { name: 'MOTOR_PRODUCT_CODE', addr: 6302 },
  { name: 'MOUNTING_ANGLE', addr: 6281 },
  { name: 'MULTI_PURPOSE_PORT_STATUS', addr: 6268 },
  { name: 'ODOMETER', addr: 6168 },
  { name: 'OEM_BIKE_ID', addr: 6238 },
  { name: 'OEM_BIKE_MODEL_ID', addr: 6261 },
  { name: 'OEM_BRAND_IDENTIFIER', addr: 6186 },
  { name: 'OEM_BRAND_NAME', addr: 6252 },
  { name: 'OEM_FREE_TEXT_FIELD', addr: 6242 },
  { name: 'OEM_HUB_CONFIGURABLE_PORT_CONFIGURATION', addr: 6297 },
  { name: 'OEM_MANUFACTURING_DATE', addr: 6241 },
  { name: 'OEM_MANUFACTURING_LINE', addr: 6240 },
  { name: 'OEM_MANUFACTURING_LOCATION', addr: 6239 },
  { name: 'OEM_MULTI_PURPOSE_PORT_CONFIGURATION', addr: 6267 },
  { name: 'OEM_PORT_CONFIGURATION', addr: 6192 },
  { name: 'OEM_SPEED_SOURCE_CONFIGURATION', addr: 6208 },
  { name: 'OEM_THROTTLE_CONFIGURATION', addr: 6299 },
  { name: 'OEM_TORQUE_LIMITATION', addr: 6294 },
  { name: 'PART_NUMBER', addr: 6146 },
  { name: 'POWER_ON_TIME', addr: 6169 },
  { name: 'POWER_ON_TIME_WITH_MOTOR_SUPPORT', addr: 6253 },
  { name: 'PRESENT_PCB_TEMPERATURE', addr: 6276 },
  { name: 'PRODUCTION_PLANT_CODE', addr: 6220 },
  { name: 'PRODUCT_APPLICATION_AVAILABLE', addr: 6201 },
  { name: 'PRODUCT_APPLICATION_REQUIRED', addr: 6200 },
  { name: 'PRODUCT_CODE', addr: 6147 },
  { name: 'PRODUCT_LINE', addr: 6183 },
  { name: 'PRODUCT_NAME', addr: 6190 },
  { name: 'RANGE_EXTENDER_READY', addr: 6217 },
  { name: 'READ_UDAM_DEFAULT_VALUES', addr: 4241 },
  { name: 'READ_UDAM_LIMITS', addr: 4242 },
  { name: 'READ_UDAM_VALUES', addr: 4240 },
  { name: 'REAR_WHEEL_CIRCUMFERENCE_OEM', addr: 6184 },
  { name: 'REAR_WHEEL_CIRCUMFERENCE_USER', addr: 6185 },
  { name: 'REAR_WHEEL_CIRCUMFERENCE_USER_LIMITS', addr: 6191 },
  { name: 'REGIO_SPEED_APPLICATION_AVAILABLE', addr: 6205 },
  { name: 'REGIO_SPEED_APPLICATION_REQUIRED', addr: 6204 },
  { name: 'REGIO_SPEED_CONFIGURATION', addr: 6269 },
  { name: 'REQUIRED_ASSIST_MODES_LOWER', addr: 6249 },
  { name: 'REQUIRED_ASSIST_MODES_UPPER', addr: 6206 },
  { name: 'RESET_ACTIVE_ASSIST_MODES_TO_DEFAULT', addr: 4253 },
  { name: 'RESET_ALL_UDAM_VALUES', addr: 4247 },
  { name: 'RESET_RANGE_CALCULATION', addr: 4238 },
  { name: 'RESET_RIDE_STATISTICS', addr: 4237 },
  { name: 'RESET_UDAM_VALUES', addr: 4244 },
  { name: 'RIDE_STATISTICS', addr: 6223 },
  { name: 'RIM_MAGNET_TEST_STATUS', addr: 6296 },
  { name: 'RIM_MAGNET_TEST_TRIGGER', addr: 4258 },
  { name: 'ROAD_SLOPE', addr: 6173 },
  { name: 'SERIAL_NUMBER', addr: 6145 },
  { name: 'SET_UDAM_VALUES_PARAMETERS', addr: 4243 },
  { name: 'SOFTWARE_VERSION', addr: 6150 },
  { name: 'SPEED_BIKE_SIGNAL_LAMP_REQUIRED', addr: 6232 },
  { name: 'SPEED_DISPLAY_TOLERANCE', addr: 6213 },
  { name: 'SPEED_MANIPULATION_STATUS', addr: 6221 },
  { name: 'SPEED_SOURCE', addr: 6209 },
  { name: 'START_ASSIST_MODE_CONFIGURATION', addr: 6180 },
  { name: 'START_ASSIST_MODE_CONFIGURATION_OEM', addr: 6179 },
  { name: 'THROTTLE_CONFIGURATION', addr: 6300 },
  { name: 'TUNING_DETECTION', addr: 6225 },
  { name: 'UDAM_MODIFICATION_POSSIBLE', addr: 6214 },
  { name: 'WALK_ASSIST_CONFIGURATION', addr: 6182 },
  { name: 'WALK_ASSIST_CONFIGURATION_OEM', addr: 6181 },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DRIVE_UNIT_ADDRESSES };
} else if (typeof window !== 'undefined') {
  window.Bes3Addresses = { DRIVE_UNIT_ADDRESSES };
}
